# Generated by Django 5.1.7 on 2025-06-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='entry',
            name='equipment_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='facility_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='entry',
            name='system_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
