# Generated by Django 5.1.7 on 2025-06-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_entry_attachment_entry_equipment_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Core', 'Core'), ('Terminal', 'Terminal')], max_length=50)),
            ],
        ),
    ]
