# Generated by Django 5.1.7 on 2025-06-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='type',
        ),
    ]
