# Generated by Django 5.1.7 on 2025-06-25 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_remove_system_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('Core', 'Core'), ('Terminal', 'Terminal')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.system')),
            ],
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
