# Generated by Django 5.1.7 on 2025-07-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_equipmententry_delete_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmententry',
            name='quantity',
        ),
    ]
