# Generated by Django 5.1.7 on 2025-07-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmententry',
            name='equipment_brand',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
