# Generated by Django 5.1.7 on 2025-07-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0008_equipmententry_equipment_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='EquipmentDocument',
        ),
    ]
