# Generated by Django 5.1.7 on 2025-07-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0009_rename_document_equipmentdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Core', 'Core'), ('Terminal', 'Terminal')], max_length=20)),
            ],
        ),
    ]
