# Generated by Django 5.1.7 on 2025-07-08 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0010_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='entry.facility'),
        ),
    ]
