# Generated by Django 5.1.7 on 2025-07-08 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0011_system_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entry.facility'),
        ),
        migrations.CreateModel(
            name='SystemEquipmentQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.system')),
            ],
        ),
    ]
