# Generated by Django 5.1.7 on 2025-07-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0012_alter_system_facility_systemequipmentquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemequipmentquantity',
            name='doc_reference_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='systemequipmentquantity',
            name='doc_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='systemequipmentquantity',
            unique_together={('system', 'equipment_name')},
        ),
    ]
