# Generated by Django 5.1.7 on 2025-07-09 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0013_systemequipmentquantity_doc_reference_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemFacilityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.facility')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.system')),
            ],
            options={
                'unique_together': {('system', 'facility')},
            },
        ),
    ]
