# Generated by Django 5.1.7 on 2025-07-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0014_systemfacilityassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='facility',
        ),
    ]
