# Generated by Django 5.1.7 on 2025-07-09 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0015_remove_system_facility'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='systemequipmentquantity',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='systemequipmentquantity',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.facility'),
        ),
        migrations.AlterField(
            model_name='systemequipmentquantity',
            name='doc_reference_code',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemequipmentquantity',
            name='doc_version',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemequipmentquantity',
            name='equipment_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='systemequipmentquantity',
            unique_together={('system', 'facility', 'equipment_name')},
        ),
    ]
