# Generated by Django 5.1.7 on 2025-07-14 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0016_alter_systemequipmentquantity_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSIncoActEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_id', models.CharField(max_length=100)),
                ('incoming_act', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.system')),
            ],
        ),
    ]
