# Generated by Django 5.1.7 on 2025-07-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0017_msincoactentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msincoactentry',
            name='system',
        ),
    ]
