# Generated by Django 5.1.7 on 2025-07-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0018_remove_msincoactentry_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='learning_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
