# Generated by Django 5.1.7 on 2025-07-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0019_learning_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning_category',
            name='code',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
