# Generated by Django 5.1.7 on 2025-07-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0020_learning_category_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learning_category',
            name='code',
        ),
    ]
