# Generated by Django 5.1.7 on 2025-07-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0021_remove_learning_category_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=100)),
            ],
        ),
    ]
