# Generated by Django 5.1.7 on 2025-07-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0022_topicsentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicsentry',
            name='learning_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entry.learning_category'),
            preserve_default=False,
        ),
    ]
