# Generated by Django 5.1.7 on 2025-07-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0024_topicsentry_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
