# Generated by Django 5.1.7 on 2025-07-17 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0025_learningstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstep',
            name='topics_entry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entry.topicsentry'),
            preserve_default=False,
        ),
    ]
