# Generated by Django 5.1.7 on 2025-07-21 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0026_learningstep_topics_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemequipmentquantity',
            name='equipment_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entry.equipmententry'),
        ),
        migrations.AlterField(
            model_name='equipmententry',
            name='type',
            field=models.CharField(choices=[('Core', 'Core'), ('Terminal', 'Terminal'), ('Associate', 'Associate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.CharField(choices=[('Core', 'Core'), ('Terminal', 'Terminal'), ('Associate', 'Associate')], max_length=20),
        ),
    ]
