# Generated by Django 6.0 on 2026-04-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0027_systemequipmentquantity_equipment_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
