# Generated by Django 6.0 on 2026-05-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0028_alter_facility_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABDEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('abd_number', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
