# Generated by Django 6.0 on 2026-01-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ittask', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
