# Generated by Django 6.0 on 2026-05-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ms_id_full', models.CharField(max_length=255)),
                ('ms_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('abd_number', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('system', models.CharField(max_length=255)),
                ('facility', models.CharField(max_length=255)),
                ('saw_program', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=100)),
            ],
        ),
    ]
