# Generated by Django 6.0 on 2026-05-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
