# Generated by Django 6.0 on 2026-05-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0002_alter_installation_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='P4ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p4_id', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ms_ids', models.ManyToManyField(related_name='p4_entries', to='installation.installation')),
            ],
        ),
    ]
