# Generated by Django 6.0 on 2026-05-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0003_p4id'),
    ]

    operations = [
        migrations.AddField(
            model_name='p4id',
            name='saw_programs',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
