# Generated by Django 6.0 on 2026-05-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0004_p4id_saw_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='p4id',
            name='associate_ms',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
