# Generated by Django 6.0 on 2026-05-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0005_p4id_associate_ms'),
    ]

    operations = [
        migrations.CreateModel(
            name='P8ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p8_id', models.CharField(max_length=255)),
                ('p2_id', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('p4_ids', models.ManyToManyField(related_name='p8_entries', to='installation.installation')),
            ],
        ),
    ]
