# Generated by Django 6.0 on 2026-05-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0006_p8id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p8id',
            name='p4_ids',
            field=models.ManyToManyField(related_name='p8_entries', to='installation.p4id'),
        ),
    ]
