# Generated by Django 6.0 on 2026-05-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0007_alter_p8id_p4_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='P9ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p9_id', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('p8_ids', models.ManyToManyField(related_name='p9_entries', to='installation.p8id')),
            ],
        ),
    ]
