# Generated by Django 6.0 on 2026-05-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0008_p9id'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='type',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
