# Generated by Django 6.0 on 2026-06-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('facility', models.CharField(max_length=100, unique=True)),
                ('facility_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('system_code', models.CharField(max_length=50, unique=True)),
                ('system_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('rmid', models.AutoField(primary_key=True, serialize=False)),
                ('room_kks', models.CharField(max_length=100, unique=True)),
                ('room_title', models.CharField(max_length=255)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='roomwise.facility')),
            ],
        ),
        migrations.CreateModel(
            name='RoomWiseDevice',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('device_kks', models.CharField(max_length=255)),
                ('device_title', models.CharField(max_length=500)),
                ('ms_id', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='roomwise.room')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='roomwise.system')),
            ],
        ),
    ]
