# Generated by Django 6.0 on 2026-06-02 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomwise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=255)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomwise.system')),
            ],
        ),
    ]
