# Generated by Django 6.0 on 2026-06-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomwise', '0003_remove_equipment_id_equipment_eid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomwisedevice',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
