# Generated by Django 6.0 on 2026-06-03 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomwise', '0004_roomwisedevice_telephone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomwise.facility')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomwise.system')),
            ],
            options={
                'unique_together': {('facility', 'system')},
            },
        ),
    ]
