# Generated by Django 6.0 on 2026-04-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraimage',
            name='capture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cameraimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
